Andrey/home page
SHREDDING8/PetConnect pull request #10
Opened 2023-08-14 17:32 UTC by anmikhailov

2023-08-14 20:10 UTC, SHREDDING8 requested changes
В комментах написал исправь пж и все будет кул

2023-08-14 20:10 UTC, SHREDDING8 commented on PetConnect/Modules/HomePage/HomePageAssembly.swift
Сделай сначала протокол

2023-08-14 20:10 UTC, SHREDDING8 commented on PetConnect/Modules/HomePage/View/HomePageViewController.swift
Протокол лучше реализовать в extension

2023-08-15 09:58 UTC, anmikhailov commented on PetConnect/Modules/HomePage/HomePageAssembly.swift
Не совсем понял, что нужно сделать. Протокол же есть. Он в отдельном файле лежит.

2023-08-16 21:21 UTC, SHREDDING8 approved these changes

2023-08-16 21:21 UTC, merged